// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHInnyWiTXTJVS7YEcO9z-s3Kt-BcDS8',
    appId: '1:805940957579:android:14aed028de192330cbdf8e',
    messagingSenderId: '805940957579',
    projectId: 'fir-login-module-fcb05',
    storageBucket: 'fir-login-module-fcb05.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGELLx89cckTesjwRU1aiYlm4WQ2-666w',
    appId: '1:805940957579:ios:6a5266b80ce205d4cbdf8e',
    messagingSenderId: '805940957579',
    projectId: 'fir-login-module-fcb05',
    storageBucket: 'fir-login-module-fcb05.firebasestorage.app',
    iosBundleId: 'com.example.zabiraAcademy',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzbiqVaO7rSUhYGg6QFfFu8-pFJcN-sA',
    appId: '1:805940957579:web:06c95029eaee34aacbdf8e',
    messagingSenderId: '805940957579',
    projectId: 'fir-login-module-fcb05',
    authDomain: 'fir-login-module-fcb05.firebaseapp.com',
    storageBucket: 'fir-login-module-fcb05.firebasestorage.app',
    measurementId: 'G-CDJFG003SD',
  );
}
